## Create a review scrapper for https://store.steampowered.com/appreviews/730?json=1  website to fetch real time comments, reviews, ratings, comment tags, customer name using Python.

In [5]:
# import the libraries 
import pandas as pd 
import requests

import requests
import pandas as pd

# Steam Review API
url = "https://store.steampowered.com/appreviews/730?json=1"

# Get data
data = requests.get(url).json()

reviews = []

# Extract reviews
for r in data['reviews']:

    reviews.append({
        "Steam_ID": r['author']['steamid'],
        "Comment": r['review'],
        "Rating": "Positive" if r['voted_up'] else "Negative",
        "Helpful_Votes": r['votes_up']
    })

# Convert to table
df = pd.DataFrame(reviews)

# Print reviews
print(df)

# Save CSV file
df.to_csv("steam_reviews.csv", index=False)

print("Reviews saved successfully!")

In [10]:
# URL 
url ="https://store.steampowered.com/appreviews/730?json=1"
# Get the Data 
data = requests.get(url).json()
data

{'success': 1,
 'query_summary': {'num_reviews': 20,
  'review_score': 8,
  'review_score_desc': 'Very Positive',
  'total_positive': 1238101,
  'total_negative': 208522,
  'total_reviews': 1446623},
 'reviews': [{'recommendationid': '222980357',
   'author': {'steamid': '76561198152982767',
    'personaname': '`•♡ cass ♡•´',
    'persona_status': 'offline',
    'profile_url': 'https://steamcommunity.com/profiles/76561198152982767/',
    'num_games_owned': 13,
    'num_reviews': 3,
    'playtime_forever': 90240,
    'playtime_last_two_weeks': 3724,
    'playtime_at_review': 83641,
    'last_played': 1778307750,
    'avatar': '73d4b354ce1cf5ba9b621543bd1e69548bae948c'},
   'language': 'english',
   'review': 'this game will steal a part of your soul and make you a gambling addict, but you wont be able to stop...',
   'timestamp_created': 1775864333,
   'timestamp_updated': 1775864333,
   'voted_up': True,
   'votes_up': 105,
   'votes_funny': 27,
   'weighted_vote_score': '0.832684636116027832',
   'comment_count': 6,
   'steam_purchase': True,
   'received_for_free': False,
   'refunded': False,
   'written_during_early_access': False,
   'primarily_steam_deck': False,
   'app_release_date': '1345568400',
   'reactions': [{'reaction_type': 29, 'count': 12},
    {'reaction_type': 31, 'count': 2},
    {'reaction_type': 25, 'count': 1}]},
  {'recommendationid': '223226432',
   'author': {'steamid': '76561199884102578',
    'personaname': 'Nirnheim',
    'persona_status': 'in-game',
    'profile_url': 'https://steamcommunity.com/id/Nirnheim/',
    'num_games_owned': 76,
    'num_reviews': 7,
    'playtime_forever': 6899,
    'playtime_last_two_weeks': 1695,
    'playtime_at_review': 3877,
    'last_played': 1778089326,
    'avatar': '9f9b535ec4b2ecce2ab652778a9dbdccbf35a028'},
   'language': 'english',
   'review': 'Counter-Strike 2 - this isn’t a shooter, it’s a mental stability test. You go in as a normal person and come out wanting to uninstall everything. Your teammates do everything except play the game, while enemies play like it’s a tournament. Gunplay is a joke: you stand still and miss, the enemy runs and lands a headshot. Balance? Probably exists. No one explained it to me. 10 missed shots out of 10.',
   'timestamp_created': 1776149998,
   'timestamp_updated': 1776149998,
   'voted_up': True,
   'votes_up': 135,
   'votes_funny': 51,
   'weighted_vote_score': '0.830002009868621826',
   'comment_count': 13,
   'steam_purchase': True,
   'received_for_free': False,
   'refunded': False,
   'written_during_early_access': False,
   'primarily_steam_deck': False,
   'app_release_date': '1345568400',
   'reactions': [{'reaction_type': 28, 'count': 5},
    {'reaction_type': 24, 'count': 1},
    {'reaction_type': 26, 'count': 1},
    {'reaction_type': 29, 'count': 1},
    {'reaction_type': 31, 'count': 1},
    {'reaction_type': 34, 'count': 1}]},
  {'recommendationid': '223863680',
   'author': {'steamid': '76561199141679921',
    'personaname': 'Mandy_Tren',
    'persona_status': 'offline',
    'profile_url': 'https://steamcommunity.com/profiles/76561199141679921/',
    'num_games_owned': 0,
    'num_reviews': 5,
    'playtime_forever': 17882,
    'playtime_last_two_weeks': 600,
    'playtime_at_review': 17165,
    'last_played': 1778268548,
    'avatar': '14c0041b0d2155cfc9d5d206c7c2f8b1e905788c'},
   'language': 'english',
   'review': 'Very goood game if you are from Russia or you are just racist you will find lots of friends.',
   'timestamp_created': 1776884876,
   'timestamp_updated': 1776884876,
   'voted_up': True,
   'votes_up': 52,
   'votes_funny': 32,
   'weighted_vote_score': '0.81443333625793457',
   'comment_count': 0,
   'steam_purchase': True,
   'received_for_free': False,
   'refunded': False,
   'written_during_early_access': False,
   'primarily_steam_deck': False,
   'app_release_date': '1345568400',
   'reactions': [{'reaction_type': 31, 'count': 4},
    {'reaction_type': 32, 'count': 1}]},
  {'recommendationid': '223911636',
   'author': {'steamid': '76561198963608852',
    'personaname': 'Deoxy',
    'persona_status': 'offline',
    'profile_url': 'https://steamcommunity.com/profiles/76561198963608852/',
    'num_games_owned': 68,
    'num_reviews': 2,
    'playtime_forever': 78491,
    'playtime_last_two_weeks': 897,
    'playtime_at_review': 77302,
    'last_played': 1778193816,
    'avatar': '5ae5849ec4add84fa26ba72e590e472e8414d24e'},
   'language': 'english',
   'review': "Be respectful of others and avoid conflicts. Prioritize fun and camaraderie. When you lose or play poorly, analyze your mistakes and focus on improvement without blaming yourself. Communicating with your teammates and playing strategically are key to winning. Don't forget to use your microphone.",
   'timestamp_created': 1776953245,
   'timestamp_updated': 1776954935,
   'voted_up': True,
   'votes_up': 581,
   'votes_funny': 10,
   'weighted_vote_score': '0.738598465919494629',
   'comment_count': 9,
   'steam_purchase': True,
   'received_for_free': False,
   'refunded': False,
   'written_during_early_access': False,
   'primarily_steam_deck': False,
   'app_release_date': '1345568400',
   'reactions': [{'reaction_type': 29, 'count': 6},
    {'reaction_type': 26, 'count': 3},
    {'reaction_type': 25, 'count': 2},
    {'reaction_type': 32, 'count': 2},
    {'reaction_type': 24, 'count': 1}]},
  {'recommendationid': '224801315',
   'author': {'steamid': '76561199850965103',
    'personaname': 'FREE SIL3A',
    'persona_status': 'offline',
    'profile_url': 'https://steamcommunity.com/id/FREESIL3A/',
    'num_games_owned': 4,
    'num_reviews': 1,
    'playtime_forever': 9509,
    'playtime_last_two_weeks': 1310,
    'playtime_at_review': 8564,
    'last_played': 1778280084,
    'avatar': '5a05d933370305bf47fdf3ead56f46dc1a39ec66'},
   'language': 'english',
   'review': 'You play well = cheater\nYou play bad = noob\nYou do a headshot = cheater\nYou hear info and can navigate the map = cheater\nYou kill someone = cheater\nIn general this game is trash!',
   'timestamp_created': 1777950265,
   'timestamp_updated': 1777950265,
   'voted_up': False,
   'votes_up': 120,
   'votes_funny': 21,
   'weighted_vote_score': '0.726940274238586426',
   'comment_count': 10,
   'steam_purchase': True,
   'received_for_free': False,
   'refunded': False,
   'written_during_early_access': False,
   'primarily_steam_deck': False,
   'app_release_date': '1345568400',
   'reactions': [{'reaction_type': 24, 'count': 1},
    {'reaction_type': 25, 'count': 1},
    {'reaction_type': 26, 'count': 1},
    {'reaction_type': 27, 'count': 1},
    {'reaction_type': 28, 'count': 1},
    {'reaction_type': 29, 'count': 1},
    {'reaction_type': 30, 'count': 1},
    {'reaction_type': 31, 'count': 1},
    {'reaction_type': 32, 'count': 1},
    {'reaction_type': 33, 'count': 1},
    {'reaction_type': 34, 'count': 1},
    {'reaction_type': 35, 'count': 1}]},
  {'recommendationid': '223755603',
   'author': {'steamid': '76561198878876128',
    'personaname': 'Ropz',
    'persona_status': 'offline',
    'profile_url': 'https://steamcommunity.com/profiles/76561198878876128/',
    'num_games_owned': 0,
    'num_reviews': 1,
    'playtime_forever': 11216,
    'playtime_last_two_weeks': 1,
    'playtime_at_review': 11213,
    'last_played': 1778162415,
    'avatar': 'd988eebf62bc6d8db48267d49b2ee1712601224f'},
   'language': 'english',
   'review': 'Hackers hackers hackers everygame, valve doesnt care since they make ♥♥♥♥♥♥♥ of money from this game regardless',
   'timestamp_created': 1776752542,
   'timestamp_updated': 1776752542,
   'voted_up': False,
   'votes_up': 84,
   'votes_funny': 11,
   'weighted_vote_score': '0.72029566764831543',
   'comment_count': 0,
   'steam_purchase': True,
   'received_for_free': False,
   'refunded': False,
   'written_during_early_access': False,
   'primarily_steam_deck': False,
   'app_release_date': '1345568400',
   'reactions': [{'reaction_type': 28, 'count': 4},
    {'reaction_type': 32, 'count': 2}]},
  {'recommendationid': '223361502',
   'author': {'steamid': '76561199577366977',
    'personaname': 'Laurence',
    'persona_status': 'offline',
    'profile_url': 'https://steamcommunity.com/profiles/76561199577366977/',
    'num_games_owned': 36,
    'num_reviews': 2,
    'playtime_forever': 6987,
    'playtime_last_two_weeks': 397,
    'playtime_at_review': 6467,
    'last_played': 1778140288,
    'avatar': 'b9ddcb71bb73737868adea917af0be56caf9431d'},
   'language': 'english',
   'review': "very interesting game I broke two mice and headphones and a phone and I don't have a phone right now so I'm playing CS",
   'timestamp_created': 1776331839,
   'timestamp_updated': 1776331839,
   'voted_up': True,
   'votes_up': 32,
   'votes_funny': 42,
   'weighted_vote_score': '0.708754777908325195',
   'comment_count': 3,
   'steam_purchase': True,
   'received_for_free': False,
   'refunded': False,
   'written_during_early_access': False,
   'primarily_steam_deck': False,
   'app_release_date': '1345568400',
   'reactions': [{'reaction_type': 30, 'count': 1},
    {'reaction_type': 34, 'count': 1}]},
  {'recommendationid': '224611003',
   'author': {'steamid': '76561199127701778',
    'personaname': 'ℝ𝕒𝕗𝕥𝕪𝕫𝕒',
    'persona_status': 'offline',
    'profile_url': 'https://steamcommunity.com/id/Raftyza/',
    'num_games_owned': 428,
    'num_reviews': 22,
    'playtime_forever': 35304,
    'playtime_last_two_weeks': 0,
    'playtime_at_review': 35304,
    'last_played': 1773962921,
    'avatar': '359f874d35967be2a64706e6f1981d4a384face0'},
   'language': 'english',
   'review': 'After 580 hours, I can confidently say my mental health has taken a scenic route straight off a cliff \nNA Premier is a comedy show. I’d genuinely rather play on EU 150+ ping than queue up with teammates who treat comms like a myth, strategy like a rumor, and teamwork like a personal attack.',
   'timestamp_created': 1777743852,
   'timestamp_updated': 1777743852,
   'voted_up': False,
   'votes_up': 22,
   'votes_funny': 6,
   'weighted_vote_score': '0.721068024635314941',
   'comment_count': 11,
   'steam_purchase': True,
   'received_for_free': False,
   'refunded': False,
   'written_during_early_access': False,
   'primarily_steam_deck': False,
   'app_release_date': '1345568400',
   'hardware': {'manufacturer': 'ASUS',
    'model': 'System Product Name',
    'dx_video_card': 'NVIDIA GeForce RTX 4070',
    'dx_vendorid': 4318,
    'dx_deviceid': 9993,
    'num_gpu': 1,
    'system_ram': '32652',
    'os': 'Windows 11',
    'cpu_vendor': 'AuthenticAMD',
    'cpu_name': 'AMD Ryzen 7 5700X 8-Core Processor             ',
    'gaming_device_type': 1,
    'dx_driver_version': '32.0.15.9597',
    'adapter_description': 'NVIDIA GeForce RTX 4070',
    'driver_version': '32.0.15.9597',
    'driver_date': '2026-3-17',
    'vram_size': 12012,
    'screen_width': None,
    'screen_height': None},
   'reactions': [{'reaction_type': 28, 'count': 3},
    {'reaction_type': 26, 'count': 1},
    {'reaction_type': 29, 'count': 1}]},
  {'recommendationid': '223710848',
   'author': {'steamid': '76561198141430579',
    'personaname': 'Vincendio',
    'persona_status': 'offline',
    'profile_url': 'https://steamcommunity.com/id/vincendio/',
    'num_games_owned': 2070,
    'num_reviews': 242,
    'playtime_forever': 5873,
    'playtime_last_two_weeks': 0,
    'playtime_at_review': 5775,
    'last_played': 1777061986,
    'avatar': '44efd34e3995b1c261de68fa542749086caaa2c9'},
   'language': 'english',
   'review': 'Get yourself a friend, play wingman, go do absolutely silly strats until the enemy team gets so pissed they get tilted and cant play properly, win. \n\nCS2 is a game of mental fortitude',
   'timestamp_created': 1776699350,
   'timestamp_updated': 1776699350,
   'voted_up': True,
   'votes_up': 18,
   'votes_funny': 3,
   'weighted_vote_score': '0.662673056125640869',
   'comment_count': 4,
   'steam_purchase': True,
   'received_for_free': False,
   'refunded': False,
   'written_during_early_access': False,
   'primarily_steam_deck': False,
   'app_release_date': '1345568400',
   'reactions': [{'reaction_type': 34, 'count': 1}]},
  {'recommendationid': '222957693',
   'author': {'steamid': '76561198728124380',
    'personaname': 'gone',
    'persona_status': 'offline',
    'profile_url': 'https://steamcommunity.com/profiles/76561198728124380/',
    'num_games_owned': 0,
    'num_reviews': 1,
    'playtime_forever': 7147,
    'playtime_last_two_weeks': 1366,
    'playtime_at_review': 3733,
    'last_played': 1778127625,
    'avatar': 'fef49e7fa7e1997310d705b2a6158ff8dc1cdfeb'},
   'language': 'english',
   'review': '>get prime\r\n>play cs2\r\n>get matched against hackers\r\n>trust factor goes down anyway\r\n>few days later get put in a hvh match with nearly everyone hacking\r\n>one of the guys is literally called "Mr. VAC" using rage cheats\r\n\r\nyou know, I got into this game after years of not being able to play it and I wasted money on prime just for this horrid ass experience, wow.\r\n\r\napparently to get a good trust factor all I have to do is get an expensive skin\r\n... don\'t think I can do that while I have absolutely no money (and even if I had any, it wouldn\'t matter because I\'m from a third world country where I can\'t afford SH*T)\r\n\r\nI\'m cooked\r\nand I\'m not touching this game till there\'s another way to get a better trust factor\r\n\r\nbecause getting matched against bots in deathmatch, getting matched against cheaters and maybe getting cheaters on my team as well, I can\'t f**cking enjoy this sh*t like this, I\'m done',
   'timestamp_created': 1775841290,
   'timestamp_updated': 1775841290,
   'voted_up': False,
   'votes_up': 24,
   'votes_funny': 1,
   'weighted_vote_score': '0.650421202182769775',
   'comment_count': 1,
   'steam_purchase': True,
   'received_for_free': False,
   'refunded': False,
   'written_during_early_access': False,
   'primarily_steam_deck': False,
   'app_release_date': '1345568400',
   'hardware': {'manufacturer': 'HP',
    'model': 'Victus by HP Gaming Laptop 15-fb0xxx',
    'dx_video_card': 'NVIDIA GeForce GTX 1650',
    'dx_vendorid': 4318,
    'dx_deviceid': 8093,
    'num_gpu': 1,
    'system_ram': '14173',
    'os': 'Windows 11',
    'cpu_vendor': 'AuthenticAMD',
    'cpu_name': 'AMD Ryzen 5 5600H with Radeon Graphics         ',
    'gaming_device_type': 1,
    'dx_driver_version': '32.0.15.9174',
    'adapter_description': 'NVIDIA GeForce GTX 1650',
    'driver_version': '32.0.15.9174',
    'driver_date': '2025-12-30',
    'vram_size': 3935,
    'screen_width': 1920,
    'screen_height': 1080},
   'reactions': []},
  {'recommendationid': '223331027',
   'author': {'steamid': '76561199813772035',
    'personaname': 'Tus1s',
    'persona_status': 'offline',
    'profile_url': 'https://steamcommunity.com/profiles/76561199813772035/',
    'num_games_owned': 9,
    'num_reviews': 1,
    'playtime_forever': 65779,
    'playtime_last_two_weeks': 1448,
    'playtime_at_review': 63359,
    'last_played': 1778269100,
    'avatar': 'f8c2f5bb8411ab39f969a7344f26648e00ece26e'},
   'language': 'english',
   'review': 'Counter-Strike 2 feels like Valve took a legendary game, put it through a washing machine, and forgot to check if anything still works afterward.\r\n\r\nSure, the smoke physics are fancy now—great, I can’t see anything in higher resolution. It’s like being blinded, but in 4K. Every match is a coin flip between a tactical masterpiece and five people running around like they just discovered the keyboard yesterday.\r\n\r\nThe servers? Amazing. I love getting shot after I’ve already taken cover. It really adds that “time travel” mechanic no one asked for.\r\n\r\nAnd then there’s playing with my friend Toivo105. Watching him play is like observing a scientific study on how many wrong decisions a human can make in 30 seconds. He moves like he’s permanently surprised, buys weapons like he’s shopping blindfolded, and somehow turns every round into a mystery novel where the main question is: “How did it go this wrong?” You don’t get mad—you just sit there, impressed in a deeply concerned way.\r\n\r\nThe ranking system also deserves an award for confusion. I’ve seen better organization in a sock drawer during an earthquake.\r\n\r\nYet somehow, despite the chaos, the bugs, and the emotional damage, I keep coming back. At this point, I’m not playing to win—I’m playing to see what new and creative way the game will disappoint me next.\r\n\r\n10/10 would uninstall and reinstall again at 3AM.',
   'timestamp_created': 1776284770,
   'timestamp_updated': 1776284770,
   'voted_up': False,
   'votes_up': 6,
   'votes_funny': 4,
   'weighted_vote_score': '0.588583946228027344',
   'comment_count': 1,
   'steam_purchase': True,
   'received_for_free': False,
   'refunded': False,
   'written_during_early_access': False,
   'primarily_steam_deck': False,
   'app_release_date': '1345568400',
   'reactions': [{'reaction_type': 24, 'count': 1}]},
  {'recommendationid': '223433989',
   'author': {'steamid': '76561198715882977',
    'personaname': '錯覚',
    'persona_status': 'offline',
    'profile_url': 'https://steamcommunity.com/id/Lagu4ka/',
    'num_games_owned': 0,
    'num_reviews': 1,
    'playtime_forever': 6458,
    'playtime_last_two_weeks': 912,
    'playtime_at_review': 357,
    'last_played': 1777227146,
    'avatar': '09f5e43de6c29ee618826b579f21b718ba61a279'},
   'language': 'english',
   'review': "Absolutely unplayable. CS2 is a massive downgrade from CS:GO, but the worst part is the completely broken anti-cheat. The game is absolutely infested with cheaters right now. It feels like every single match has someone blatantly using wallhacks or an aimbot. VAC is a complete joke. Don't waste your time or sanity downloading this hacker playground.",
   'timestamp_created': 1776421254,
   'timestamp_updated': 1776421254,
   'voted_up': False,
   'votes_up': 14,
   'votes_funny': 0,
   'weighted_vote_score': '0.58423924446105957',
   'comment_count': 0,
   'steam_purchase': True,
   'received_for_free': False,
   'refunded': False,
   'written_during_early_access': False,
   'primarily_steam_deck': False,
   'app_release_date': '1345568400',
   'reactions': []},
  {'recommendationid': '223720021',
   'author': {'steamid': '76561199200690842',
    'personaname': 'Ozzi',
    'persona_status': 'offline',
    'profile_url': 'https://steamcommunity.com/profiles/76561199200690842/',
    'num_games_owned': 10,
    'num_reviews': 1,
    'playtime_forever': 11570,
    'playtime_last_two_weeks': 536,
    'playtime_at_review': 10819,
    'last_played': 1778184074,
    'avatar': 'e2350c07681e96a13391afad2cf6920e1c790e83'},
   'language': 'english',
   'review': 'I love this game its worth ur time. Its maybe hard in the beginning but u will get it with time.',
   'timestamp_created': 1776707728,
   'timestamp_updated': 1776707728,
   'voted_up': True,
   'votes_up': 5,
   'votes_funny': 0,
   'weighted_vote_score': '0.570355534553527832',
   'comment_count': 0,
   'steam_purchase': True,
   'received_for_free': False,
   'refunded': False,
   'written_during_early_access': False,
   'primarily_steam_deck': False,
   'app_release_date': '1345568400',
   'reactions': [{'reaction_type': 34, 'count': 1}]},
  {'recommendationid': '223207616',
   'author': {'steamid': '76561199786360330',
    'personaname': 'R₂',
    'persona_status': 'offline',
    'profile_url': 'https://steamcommunity.com/id/Cypress888/',
    'num_games_owned': 0,
    'num_reviews': 1,
    'playtime_forever': 14269,
    'playtime_last_two_weeks': 39,
    'playtime_at_review': 13789,
    'last_played': 1778084753,
    'avatar': 'c9239c9845b1b7ec6458942f511737adf9fe585d'},
   'language': 'english',

In [14]:
#  Store in Array 
reviews=[]
# Extract Reviews 
for r in data['reviews']:

    reviews.append({
        
        "Stream_Id":r["author"]["steamid"],
        "Comments":r['review'],
        "Rating" : "Positive" if r['voted_up'] else "Negative",
        "Commant_TAg" : "Useful"  if r['votes_up'] else "not Useful"
     })
# reviews

In [17]:
# convert to the table 
df =pd.DataFrame(reviews)
df

,Stream_Id,Comments,Rating,Commant_TAg
0,76561198152982767,this game will steal a part of your soul and m...,Positive,Useful
1,76561199884102578,"Counter-Strike 2 - this isn’t a shooter, it’s ...",Positive,Useful
2,76561199141679921,Very goood game if you are from Russia or you ...,Positive,Useful
3,76561198963608852,Be respectful of others and avoid conflicts. P...,Positive,Useful
4,76561199850965103,You play well = cheater\nYou play bad = noob\n...,Negative,Useful
5,76561198878876128,"Hackers hackers hackers everygame, valve doesn...",Negative,Useful
6,76561199577366977,very interesting game I broke two mice and hea...,Positive,Useful
7,76561199127701778,"After 580 hours, I can confidently say my ment...",Negative,Useful
8,76561198141430579,"Get yourself a friend, play wingman, go do abs...",Positive,Useful
9,76561198728124380,>get prime\r\n>play cs2\r\n>get matched agains...,Negative,Useful
10,76561199813772035,Counter-Strike 2 feels like Valve took a legen...,Negative,Useful
11,76561198715882977,Absolutely unplayable. CS2 is a massive downgr...,Negative,Useful
12,76561199200690842,I love this game its worth ur time. Its maybe ...,Positive,Useful
13,76561199786360330,bullllllllllshet game............... the bulls...,Negative,Useful
14,76561199492902908,Great Game.\nGreat Graphic.\nSo many Toxic Pla...,Positive,Useful
15,76561198979046439,If you hate yourself and having any sort of fu...,Negative,Useful
16,76561199561600477,One of the best game before now its just piece...,Negative,Useful
17,76561197981915477,Counter-Strike 2 is a fantastic game if you en...,Positive,Useful
18,76561198790397030,"Bom jogo, o problema são os xitters.Bom jogo, ...",Positive,Useful
19,76561198815564182,the inability to tab out of this game without ...,Negative,Useful

In [20]:
# save to .csv File all the Data 
df.to_csv("Stream_Review.csv" , index=False )
print("Review Successfully saved")
df.head()

Review Successfully saved

,Stream_Id,Comments,Rating,Commant_TAg
0,76561198152982767,this game will steal a part of your soul and m...,Positive,Useful
1,76561199884102578,"Counter-Strike 2 - this isn’t a shooter, it’s ...",Positive,Useful
2,76561199141679921,Very goood game if you are from Russia or you ...,Positive,Useful
3,76561198963608852,Be respectful of others and avoid conflicts. P...,Positive,Useful
4,76561199850965103,You play well = cheater\nYou play bad = noob\n...,Negative,Useful